server:
    port: 8081
spring:
  application:
    name:  heson-microservice-item
eureka:
    client:
        registerWithEureka: true
        fetchRegister: false
    serviceUrl:
        defaultZone: http://127.0.0.1:8761:/eureka
    instance:
        prefer-ip-address: true