server:
  port: 8762
spring:
  application:
    name:  heson-microservice-eureka
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/